# SPDX-FileCopyrightText: 2024 Alejandro AR
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure FreshRSS paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ freshrss_uid }}"
    group: "{{ freshrss_gid }}"
  with_items:
    - "{{ freshrss_base_path }}"
    - "{{ freshrss_data_path }}"
    - "{{ freshrss_extensions_path }}"

- name: Ensure FreshRSS support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ freshrss_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ freshrss_uid }}"
    group: "{{ freshrss_gid }}"
  with_items:
    - env
    - labels

- name: Ensure FreshRSS container image is pulled
  community.docker.docker_image:
    name: "{{ freshrss_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ freshrss_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else freshrss_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure FreshRSS container network is created
  community.general.docker_network:
    name: "{{ freshrss_container_network }}"
    driver: bridge

- name: Ensure FreshRSS systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/freshrss.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ freshrss_identifier }}.service"
    mode: "0644"
