# SPDX-FileCopyrightText: 2024 Alejandro AR
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- block:
    - when: freshrss_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: freshrss_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-freshrss
    - install-all
    - install-freshrss

- block:
    - when: not freshrss_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-freshrss
