# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Alejandro AR
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform FreshRSS installation tasks
  when: freshrss_enabled | bool
  tags:
    - setup-all
    - setup-freshrss
    - install-all
    - install-freshrss
  block:
    - name: Validate FreshRSS configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install FreshRSS
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform tasks to print database credentials for FreshRSS
  when: freshrss_enabled | bool
  tags:
    - print-freshrss-db-credentials
  block:
    - name: Print database credentials for FreshRSS
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/print_db_credentials.yml"

- name: Perform FreshRSS uninstallation tasks
  when: not freshrss_enabled | bool
  tags:
    - setup-all
    - setup-freshrss
  block:
    - name: Uninstall FreshRSS
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
