# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Alejandro AR
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of FreshRSS systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freshrss_identifier }}.service"
  register: freshrss_service_stat

- name: Uninstall FreshRSS systemd services and files
  when: freshrss_service_stat.stat.exists | bool
  block:
    - name: Ensure FreshRSS systemd service is stopped
      ansible.builtin.service:
        name: "{{ freshrss_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FreshRSS systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freshrss_identifier }}.service"
        state: absent

    - name: Ensure FreshRSS support files do not exist
      ansible.builtin.file:
        path: "{{ freshrss_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure FreshRSS local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freshrss_data_path }}"
      register: freshrss_data_path_deletion_result
      changed_when: freshrss_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreshRSS local extensions path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freshrss_extensions_path }}"
      register: freshrss_extensions_path_deletion_result
      changed_when: freshrss_extensions_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreshRSS base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freshrss_base_path }}"
      register: freshrss_base_path_deletion_result
      changed_when: freshrss_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreshRSS container network does not exist
      when: freshrss_container_network_deletion_enabled
      block:
        - name: Ensure FreshRSS container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ freshrss_container_network }}"
            state: absent
          register: freshrss_network_deletion_result

        - name: Ensure FreshRSS container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ freshrss_container_network }}
          register: freshrss_network_deletion_result
          changed_when: freshrss_container_network in freshrss_network_deletion_result.stdout

- name: Check existence of FreshRSS local data path
  ansible.builtin.stat:
    path: "{{ freshrss_data_path }}"
  register: freshrss_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if FreshRSS local data remains
  when: freshrss_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local FreshRSS instance has been removed, some old data remains in `" + freshrss_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of FreshRSS extensions path
  ansible.builtin.stat:
    path: "{{ freshrss_extensions_path }}"
  register: freshrss_extensions_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if FreshRSS extensions remain
  when: freshrss_extensions_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local FreshRSS instance has been removed, some extensions remain in `" + freshrss_extensions_path + "`. Feel free to delete it."
        ]
      }}
