# SPDX-FileCopyrightText: 2024 Alejandro AR
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of FreshRSS systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freshrss_identifier }}.service"
  register: freshrss_service_stat

- name: Uninstall FreshRSS systemd services and files
  when: freshrss_service_stat.stat.exists | bool
  block:
    - name: Ensure FreshRSS systemd service is stopped
      ansible.builtin.service:
        name: "{{ freshrss_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FreshRSS systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freshrss_identifier }}.service"
        state: absent

    - name: Ensure FreshRSS path doesn't exist
      ansible.builtin.file:
        path: "{{ freshrss_base_path }}"
        state: absent
