# SPDX-FileCopyrightText: 2024 Alejandro AR
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "freshrss_http_header_content_permission_policy", "new": "freshrss_http_header_permissions_policy" }

- name: Fail if required FreshRSS settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - freshrss_identifier
    - freshrss_uid
    - freshrss_gid
    - freshrss_hostname
    - freshrss_path_prefix
    - freshrss_container_network

- name: Fail if FreshRSS database type invalid
  ansible.builtin.fail:
    msg: >-
      freshrss_database_type must be 'mysql', 'postgres' or 'sqlite'
  when: "freshrss_database_type not in ['mysql', 'postgres', 'sqlite']"

- name: Fail if required FreshRSS + MySQL integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `freshrss_database_type` is `mysql`
  when: "freshrss_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - freshrss_database_mysql_hostname
    - freshrss_database_mysql_password

- name: Fail if required FreshRSS + Postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `freshrss_database_type` is `postgres`
  when: "freshrss_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - freshrss_database_hostname
    - freshrss_database_password

- name: Run if Traefik is enabled
  when: freshrss_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required FreshRSS Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - freshrss_container_labels_traefik_hostname
        - freshrss_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `freshrss_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if freshrss_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          freshrss_container_labels_traefik_path_prefix (`{{ freshrss_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/freshrss`).
      when: "freshrss_container_labels_traefik_path_prefix != '/' and freshrss_container_labels_traefik_path_prefix[-1] == '/'"
